services:
  json-server:
    build: .
    container_name: "jsonserver"
    ports:
      - "3000:3000"
    volumes:
      - ./app/data.json:/app/data.json
      - ./public:/app/public
    environment:
      - NODE_ENV=production